# Model Architecture
n_layer: 8
num_layers: 3
n_head: 15
n_embd: 150
bias: true
dropout: 0.2

# Training Settings
batch_size: 256
block_size: 1250
vocab_size: 201
learning_rate: 0.0001
max_epochs: 100
log_interval: 20
checkpoint_dir: "checkpoints"