# Model Architecture

n_layer: 8 # Number of Tranformer blocks
num_layers: 3 # This is a fix parameter defining gow many layers the INR has
n_head: 20 # Number of attention heads
n_embd: 200 # embedding dimension
bias: true
dropout: 0.2

# Training Settings
batch_size: 512
block_size: 170
vocab_size: 152
learning_rate: 0.01
max_epochs: 20
log_interval: 100
checkpoint_dir: "checkpoints"